"""Agent 2 – The Brain: ratio analysis, CMA, Indian GAAP."""

from __future__ import annotations

from typing import Any

COMPLIANCE_NOTES = {
    "header": "Compliance Notes",
    "body": (
        "This report is generated by KC FinanceHub for analytical purposes only. "
        "It does not constitute statutory attestation. Financial analysis follows "
        "Indian AS/Ind-AS. Income tax projections adhere to the Income Tax Act, 1961. "
        "GST compliance follows the CGST Act, 2017."
    ),
}


def validate_document(document_id: str, org_id: str) -> None:
    """Data Gatekeeper validation stub – extend with extraction pipeline."""
    if not document_id or not org_id:
        raise ValueError("Invalid document or org")
    
    # TODO: Fetch document from Supabase, parse PDF, and update status in `documents` table.


def generate_financial_report(
    org_id: str,
    document_ids: list[str],
    report_type: str,
) -> dict[str, Any]:
    """Generate AI financial report with mandatory Compliance Notes."""
    # TODO: Fetch real data from `document_ids`, process with LLM, and calculate dynamic ratios.
    # Currently returning hardcoded dummy ratios for demonstration.
    ratios = {
        "current_ratio": 1.85,
        "quick_ratio": 1.22,
        "debt_equity": 0.64,
        "net_profit_margin_pct": 8.4,
        "return_on_equity_pct": 14.2,
    }

    return {
        "report_type": report_type,
        "org_id": org_id,
        "document_ids": document_ids,
        "framework": "Ind AS / Indian GAAP",
        "ratio_analysis": ratios,
        "cma_summary": (
            "Working capital assessment indicates adequate liquidity. "
            "Debt levels are within acceptable limits for MSME lending norms."
        ),
        "income_tax_projection": {
            "basis": "Income Tax Act, 1961",
            "estimated_liability_inr": None,
            "note": "Requires validated P&L and schedule inputs.",
        },
        "gst_observations": {
            "basis": "CGST Act, 2017",
            "note": "Cross-verify with GSTR-3B filings in Watchdog module.",
        },
        "compliance_notes": COMPLIANCE_NOTES,
    }
